// Utility helpers for working with default layouts.

export const DEFAULT_HOMEPAGE_LAYOUT = [
  {
    id: "profile",
    type: "profile",
    col: 3,
    row: 0,
    w: 7,
    h: 3,
    locked: false,
    pinned: true,
    settings: {
    },
  },
  {
    id: "about",
    type: "about",
    col: 0,
    row: 3,
    w: 10,
    h: 3,
    locked: false,
    pinned: true,
    settings: {
      adjusted: true,
    },
  },
  {
    id: "contact",
    type: "contact",
    col: 4,
    row: 16,
    w: 6,
    h: 3,
    locked: false,
    pinned: true,
    settings: {},
  },
  {
    id: "single-game",
    type: "single-game",
    col: 21,
    row: 9,
    w: 13,
    h: 10,
    locked: false,
    pinned: true,
    settings: {
      gameId: "pullbackracers",
    },
  },
  {
    id: "single-game-3",
    type: "single-game",
    col: 10,
    row: 0,
    w: 13,
    h: 9,
    locked: false,
    pinned: true,
    settings: {
      gameId: "gamblelite",
    },
  },
  {
    id: "games",
    type: "games",
    col: 0,
    row: 6,
    w: 10,
    h: 10,
    locked: false,
    pinned: false,
    settings: {
      adjusted: true,
    },
  },
  {
    id: "profile-picture",
    type: "profile-picture",
    col: 0,
    row: 0,
    w: 3,
    h: 3,
    locked: false,
    pinned: false,
    settings: {
    },
  },
  {
    id: "cv",
    type: "cv",
    col: 0,
    row: 16,
    w: 4,
    h: 3,
    locked: false,
    pinned: false,
    settings: {},
  },
  {
    id: "single-game-4",
    type: "single-game",
    col: 10,
    row: 9,
    w: 11,
    h: 10,
    locked: false,
    pinned: false,
    settings: {
      gameId: "Forgekeepers",
    },
  },
  {
    id: "single-game-5",
    type: "single-game",
    col: 23,
    row: 0,
    w: 11,
    h: 9,
    locked: false,
    pinned: false,
    settings: {
      gameId: "gp3",
    },
  },
];

export const DEFAULT_GAME_DETAIL_LAYOUT = [
  {
    id: "back-button",
    type: "back-button",
    col: 0,
    row: 0,
    w: 3,
    h: 2,
    locked: true,
    pinned: false,
  },
  {
    id: "game-info",
    type: "game-info",
    col: 3,
    row: 0,
    w: 31,
    h: 2,
    locked: false,
    pinned: true,
  },
  {
    id: "game-description",
    type: "game-description",
    col: 0,
    row: 11,
    w: 12,
    h: 5,
    locked: false,
    pinned: true,
  },
  {
    id: "game-image",
    type: "game-image",
    col: 0,
    row: 2,
    w: 12,
    h: 9,
    locked: false,
    pinned: true,
  },
  {
    id: "game-development-info",
    type: "game-development-info",
    col: 12,
    row: 2,
    w: 22,
    h: 17,
    locked: false,
    pinned: true,
  },
  {
    id: "game-details",
    type: "game-details",
    col: 0,
    row: 16,
    w: 12,
    h: 3,
    locked: false,
    pinned: true,
  },
];

export const DEFAULT_HOMEPAGE_LAYOUT_MOBILE = [
  {
    id: "profile",
    type: "profile",
    col: 3,
    row: 0,
    w: 5,
    h: 3,
    locked: false,
    pinned: true,
    settings: {
    },
  },
  {
    id: "about",
    type: "about",
    col: 0,
    row: 3,
    w: 8,
    h: 3,
    locked: false,
    pinned: true,
    settings: {
      adjusted: true,
    },
  },
  {
    id: "contact",
    type: "contact",
    col: 0,
    row: 37,
    w: 5,
    h: 3,
    locked: false,
    pinned: true,
    settings: {},
  },
  {
    id: "single-game",
    type: "single-game",
    col: 0,
    row: 15,
    w: 8,
    h: 9,
    locked: false,
    pinned: true,
    settings: {
      gameId: "pullbackracers",
    },
  },
  {
    id: "single-game-3",
    type: "single-game",
    col: 0,
    row: 6,
    w: 8,
    h: 9,
    locked: false,
    pinned: true,
    settings: {
      gameId: "gamblelite",
    },
  },
  {
    id: "games",
    type: "games",
    col: 0,
    row: 24,
    w: 8,
    h: 13,
    locked: false,
    pinned: false,
    settings: {
      adjusted: true,
    },
  },
  {
    id: "profile-picture",
    type: "profile-picture",
    col: 0,
    row: 0,
    w: 3,
    h: 3,
    locked: false,
    pinned: false,
    settings: {
    },
  },
  {
    id: "cv",
    type: "cv",
    col: 5,
    row: 37,
    w: 3,
    h: 3,
    locked: false,
    pinned: false,
    settings: {},
  },
];

export const DEFAULT_GAME_DETAIL_LAYOUT_MOBILE = [
  {
    id: "back-button",
    type: "back-button",
    col: 0,
    row: 0,
    w: 3,
    h: 2,
    locked: true,
    pinned: false,
  },
  {
    id: "game-info",
    type: "game-info",
    col: 0,
    row: 2,
    w: 8,
    h: 4,
    locked: false,
    pinned: true,
  },
  {
    id: "game-description",
    type: "game-description",
    col: 0,
    row: 14,
    w: 8,
    h: 5,
    locked: false,
    pinned: true,
  },
  {
    id: "game-image",
    type: "game-image",
    col: 0,
    row: 6,
    w: 8,
    h: 8,
    locked: false,
    pinned: true,
  },
  {
    id: "game-development-info",
    type: "game-development-info",
    col: 0,
    row: 19,
    w: 8,
    h: 17,
    locked: false,
    pinned: false,
  },
  {
    id: "game-details",
    type: "game-details",
    col: 0,
    row: 36,
    w: 8,
    h: 4,
    locked: false,
    pinned: false,
  },
];

export const DEFAULT_CV_DETAIL_LAYOUT = [
  {
    id: "back-button",
    type: "back-button",
    col: 0,
    row: 0,
    w: 3,
    h: 1,
    locked: true,
    pinned: false,
    settings: {},
  },
  {
    id: "profile",
    type: "profile",
    col: 3,
    row: 0,
    w: 4,
    h: 4,
    locked: false,
    pinned: true,
    settings: {},
  },
  {
    id: "profile-picture",
    type: "profile-picture",
    col: 0,
    row: 1,
    w: 3,
    h: 3,
    locked: false,
    pinned: true,
    settings: {
    },
  },
  {
    id: "experience",
    type: "experience",
    col: 0,
    row: 4,
    w: 13,
    h: 7,
    locked: false,
    pinned: true,
    settings: {},
  },
  {
    id: "technical-skills",
    type: "technical-skills",
    col: 6,
    row: 16,
    w: 7,
    h: 3,
    locked: false,
    pinned: true,
    settings: {},
  },
  {
    id: "education",
    type: "education",
    col: 7,
    row: 0,
    w: 6,
    h: 4,
    locked: false,
    pinned: true,
    settings: {},
  },
  {
    id: "languages",
    type: "languages",
    col: 0,
    row: 16,
    w: 6,
    h: 3,
    locked: false,
    pinned: true,
    settings: {},
  },
  {
    id: "projects",
    type: "projects",
    col: 0,
    row: 11,
    w: 13,
    h: 5,
    locked: false,
    pinned: true,
    settings: {},
  },
];

/**
 * Set the default layouts for both main page and game detail page
 * This function can be called from the browser console or imported
 */
export const formatLayoutSnippet = (layout, exportName) => {
  const formatted = JSON.stringify(layout, null, 2);
  return `export const ${exportName} = ${formatted};`;
};

export const copyLayoutSnippet = async (layout, exportName) => {
  const snippet = formatLayoutSnippet(layout, exportName);
  if (typeof navigator !== "undefined" && navigator.clipboard) {
    await navigator.clipboard.writeText(snippet);
  }
  return snippet;
};

// If running in browser console, expose the helpers
if (typeof window !== "undefined") {
  window.formatLayoutSnippet = formatLayoutSnippet;
  window.copyLayoutSnippet = copyLayoutSnippet;
}
